/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 yyy.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model33(props) {
  const { nodes, materials } = useGLTF('/yyy.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} >
      <meshStandardMaterial
      color="red"
      /></mesh>
    </group>
  )
}

useGLTF.preload('/yyy.gltf')
